### ISSUE TITLE
Feature request: Source dependency

### ISSUE THREAD

**Issue by szermatt** [emacs-eldev/eldev#111]
It would be very useful to be able to tell eldev to fetch dependency from some other repository instead of from archives.

A problem I'm having right now is that I have a test dependency that is not (yet) available in any archives.
What would be the right way of telling eldev to use that dependency?

A nice solution would be to be able to specify a source dependency which would fetch a package without using an archive, similar to `package-vc-checkout`, something like this:

``
 (eldev-add-extra-dependencies 'test '(:package mydep :source "https://github.com/myproject/mydep.git")
``

possibly with an extra key to specify a tag or version. 

Now, maybe there is already  a way to do something like that, and I just didn't see it reading the manual.

I am currently using a workaround that works [in my project](https://github.com/szermatt/mistty/blob/1affd06dfb1f65519ecf7b96777209b1f9f9489c/Eldev), so I'm not stuck, but it's definitely wrong and I would welcome a better solution: I add the dependency as a git submodule, then call `eldev-use-local-dependency` inside of `Eldev`.  

Example:
```
  (eldev-add-extra-dependencies '(test emacs) 'mydep)
  (eldev-use-local-dependency "./deps/mydep")
```
One thing doesn't work with this hack: `eldev-use-local-dependency` cannot be used anymore for its intended purpose, in `Eldev-local`  😒

**Comment by doublep** [comment]
Isn't it the feature added in 1.11 two weeks ago? Search the documentation for `eldev-use-vc-repository`.

**Comment by szermatt** [comment]
Ah, yes! Nice! Thank you! I had looked for it a while ago, I must admit. I should have re-checked before filing the bug.

**Comment by doublep** [comment]
> I should have re-checked

Best would be to subscribe to this repository releases (watch -> custom -> select "releases"). I always list new features when describing a release and it's easy to just ignore three lines when there is nothing interesting to you.

**Comment by szermatt** [comment]
That's a good idea! Done.
