### ISSUE TITLE
Allow to configure projects to have their source code in a subdirectory

### ISSUE THREAD

**Issue by doublep** [emacs-eldev/eldev#94]
Example: [Magit](https://github.com/magit/magit), where over 50 `.el` files are collected in subdirectory `lisp`, to avoid having a huge list at the top level.

While at it, it might be helpful to support _several_ directories, e.g. one for Lisp, one for resource files. Obviously needs to be optional.

Requested by [CIDER](https://github.com/clojure-emacs/cider) (@bbatsov).

**Comment by doublep** [comment]
Done in 1.8.

**Comment by bbatsov** [comment]
Thanks a lot!
